appId: org.azkadev.specta_app
# relative path to the application's icon
# icon: assets/logo.png

script:
  - echo 'Running a Script'

include: []
exclude: []
# its true by default
default_excludes: true

files:
  include: []
  exclude: []
  # its true by default
  default_excludes: true